version: '2.1'
services:
    etcd1:
        container_name: etcd_infra1
        image: gcr.io/google_containers/etcd-amd64:3.0.17
        command: |
                etcd --name infra1
                --initial-advertise-peer-urls http://172.21.161.29:2380
                --listen-peer-urls http://172.21.161.29:2380
                --listen-client-urls http://172.21.161.29:2379,http://127.0.0.1:2379
                --advertise-client-urls http://172.21.161.29:2379
                --data-dir /etcd-data.etcd
                --initial-cluster-token etcd-cluster-1
                --initial-cluster infra0=http://172.21.161.28:2380,infra1=http://172.21.161.29:2380,infra2=http://172.21.161.30:2380
                --initial-cluster-state new
        restart: always
        volumes:
           - /data/etcd-data.etcd:/etcd-data.etcd
        network_mode: "host"

